name: Continious Integration
on: push

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Psalm
              uses: docker://vimeo/psalm-github-actions

    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.2', '7.3', '7.4']
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php-versions }}
            - name: Install dependencies
              run: composer install -n --prefer-dist
            - name: Run PHPUnit unit tests
              run: vendor/bin/phpunit

    check-licenses:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: '7.4'
            -   name: Install dependencies
                run: composer install -n --prefer-dist
            -   name: Run License Checker
                run: bin/license-checker check
